services:
  - type: web
    name: isl-two-way-translator
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
